### ISSUE TITLE
how to generate dag tasks

### ISSUE THREAD

**Issue by fancyshun** [jatinpapreja/A-Novel-Task-Duplication-based-DAG-Scheduling-Algorithm-for-Heterogeneous-Environments#1]
你好，我想请问一下能不能分享一下你的任务图生成方法，谢谢啦

**Comment by jatinpapreja** [comment]
DAG generation method was not provided in the Research Paper. Only an example DAG was given in it which is already tested in the code.

**Comment by fancyshun** [comment]
I know DAG generation method was not provided in your Paper
,I want to get the code to study, could you share your code, thanks!
| |
常顺
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/10/2022 18:09 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jatinpapreja/A-Novel-Task-Duplication-based-DAG-Scheduling-Algorithm-for-Heterogeneous-Environments] how to generate dag tasks (Issue #1) |

DAG generation method was not provided in the Research Paper. Only an example DAG was given in it which is already tested in the code.

**Comment by jatinpapreja** [comment]
Code is present in "OS Research Paper Implementation.ipynb" file.

**Comment by fancyshun** [comment]
I want to know how to generate  dag, can you share the code.
| |
常顺
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/10/2022 22:25 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jatinpapreja/A-Novel-Task-Duplication-based-DAG-Scheduling-Algorithm-for-Heterogeneous-Environments] how to generate dag tasks (Issue #1) |

Code is present in "OS Research Paper Implementation.ipynb" file.

**Comment by jatinpapreja** [comment]
The function is "draw_graph" which is used for implementing DAG graph generation in the code.

**Comment by fancyshun** [comment]
Hi, I want to do an experiment on your paper and then make a report to the teacher to let everyone know about your paper.Can you share the code of TANH and DCPD. Thanks a lot.


| |
常顺
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2022 00:41 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jatinpapreja/A-Novel-Task-Duplication-based-DAG-Scheduling-Algorithm-for-Heterogeneous-Environments] how to generate dag tasks (Issue #1) |

Closed #1 as completed.

**Comment by jatinpapreja** [comment]
Sorry, we have not implemented TANH and DCPD.

**Comment by fancyshun** [comment]
How did the experiments on the TANH algorithm in the paper work
| |
常顺
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/28/2022 16:09 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jatinpapreja/A-Novel-Task-Duplication-based-DAG-Scheduling-Algorithm-for-Heterogeneous-Environments] how to generate dag tasks (Issue #1) |

Sorry, we have not implemented TANH and DCPD.

**Comment by jatinpapreja** [comment]
The comparison plots made are hardcoded.

**Comment by fancyshun** [comment]
How is the experiment in Chapter 4 done? How to hardcode more than 50,000 tasks




| |
常顺
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/29/2022 02:19 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jatinpapreja/A-Novel-Task-Duplication-based-DAG-Scheduling-Algorithm-for-Heterogeneous-Environments] how to generate dag tasks (Issue #1) |

The comparison plots made are hardcoded.

**Comment by jatinpapreja** [comment]
Sorry to disappoint you, but we are not the authors of the paper. We have just implemented TDCA algorithm provided in the paper.

**Comment by fancyshun** [comment]
ok，thanks a lot



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/29/2022 17:28 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [jatinpapreja/A-Novel-Task-Duplication-based-DAG-Scheduling-Algorithm-for-Heterogeneous-Environments] how to generate dag tasks (Issue #1) |

Sorry to disappoint you, but we are not the authors of the paper. We have just implemented TDCA algorithm provided in the paper.
